#!/usr/bin/env bash

docker run -v $MCVINE_RESOURCES:/opt/danse/share/mcvine/resources -v $PWD/test:/opt/danse/src/mcvine/releaser/test linjiao/mcvine-ubuntu-build:14.04 sh test

# example: docker run -v /home/linjiao/dv/mcvine-resources:/opt/mcvine/resources -v ~/dv/mcvine-releaser-git/docker/ubuntu/14.04/test/test:/opt/mcvine/test linjiao/mcvine-ubuntu-build:14.04 sh test
