#!/usr/bin/env bash

docker run linjiao/mcvine-ubuntu-build:14.04 bash /src/mcvine/builders/test /src/mcvine/build /opt/danse/share/mcvine/resources

# example: docker run -v /home/linjiao/dv/mcvine-resources:/opt/mcvine/resources -v ~/dv/mcvine-releaser-git/docker/ubuntu/14.04/test/test:/opt/mcvine/test linjiao/mcvine-ubuntu-build:14.04 sh test
