python:
  - 2.7
gsl:
  - 2.4
boost:
  - 1.66
  - 1.69
numpy:
  - 1.14.0
  - 1.16.0
journal:
  - 0.8.2

zip_keys:
  - boost
  - numpy

pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
  journal:
    max_pin: x.x.x
