python:
  - 2.7
  - 3.6
  - 3.8
gsl:
  - 2.4
boost:
  - 1.66
  - 1.66
  - 1.73
numpy:
  - 1.14.0
  - 1.14.0
  - 1.19.0
numpyext:
  - 0.1.3
bpext:
  - 0.1.4
histogram:
  - 0.3.7
drchops:
  - 2.0.3
 
zip_keys:
  - python
  - boost
  - numpy

pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
  numpyext:
    max_pin: x.x
  bpext:
    max_pin: x.x
  histogram:
    max_pin: x.x
  drchops:
    max_pin: x.x
