#!/usr/bin/env bash

. /opt/danse/bin/setup-danse.sh

rm -rf build
mkdir build
cd build
cmake .. -DDEPLOYMENT_PREFIX=/opt/danse -DCMAKE_INSTALL_PREFIX=~/dv/mcvine-releaser/output
make -j20 reconfigure-to-include-mcstas-components
make -j20 wrap-mcstas-components-cmake
