#!/usr/bin/env bash

MSG=$@

SPHINX_SRC=docs/sphinx
GH_PAGES_SRC="docs build-gh-pages"

git checkout gh-pages
rm -rf  _sources _static _images # remove old directories
git checkout master $GH_PAGES_SRC # get sphinx source
git reset HEAD
cd $SPHINX_SRC # build
make html
mv -fv $SPHINX_SRC/_build/html/* ./  # mv new html files to root
rm -rf $GH_PAGES_SRC  # remove sphinx source
git add -A  # add new files
# git ci -m "Generated gh-pages for `git log master -1 --pretty=short --abbrev-commit`" && git push origin gh-pages ; git checkout master
git commit -m "$MSG" && git push origin gh-pages
git checkout master
