#!/usr/bin/env bash

if [ $# -eq 0 ]
then
    echo	"Usage: ./buildme /path/to/mcvine/resources [cores]"
    exit 1
fi

MCVINE_RESOURCES=$1

CORES=$2
if ((CORES < 1)); then
    let CORES=`grep -c ^processor /proc/cpuinfo`
    let CORES-=1
    if ((CORES < 1)); then
	CORES = 1;
    fi
fi

echo "Building mcvine"
echo "- mcvine resoureces: $MCVINE_RESOURCES"
echo "- using $CORES cores"

. /opt/danse/bin/setup-danse.sh

rm -rf build
mkdir build
cd build
cmake .. -DDEPLOYMENT_PREFIX=/opt/danse -DCMAKE_INSTALL_PREFIX=~/dv/mcvine-releaser/output
make -j$CORES reconfigure-to-include-mcstas-components
make -j$CORES wrap-mcstas-components-cmake
make -j$CORES 
make test ARGS="-j$CORES"
