#!/usr/bin/env python
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                 Jiao Lin
#                      California Institute of Technology
#                      (C) 2006-2010  All Rights Reserved
#
# {LicenseText}
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#


import warnings
warnings.simplefilter('ignore')
import mcvine
warnings.simplefilter('default')


import mccomponents.sample.diffraction.xml

def main():
    from mcvine.applications.InstrumentBuilder import build
    components = ['source', 'sample', 'detector']
    App = build(components)
    # Change name according to base name of .pml file, e.g. "ssd1" for ssd1.pml
    app = App('ssd4_1')
    app.run()
    return

if __name__ == '__main__':
    main()

# version
# $Id$
