#!/usr/bin/env python


"""
converte events.dat to nexus file.

events.dat are generated by mcvine simulation that sends scattereted neutrons
to SEQUOIA detector system.

"""

appname = 'sequoia-events2nxs'


def run(eventfile, nxsfile, tofbinsize, type):
    print (eventfile, nxsfile)
    from mccomponents.detector.event_utils import readEvents
    events = readEvents(eventfile)
    
    prefix = 'mcvine.instruments.SEQUOIA.nxs'
    mod = '%s.%s' % (prefix, type)
    mod = __import__(mod, fromlist = [''])
    mod.write(events, tofbinsize, nxsfile)
    return
