#!/usr/bin/env python
import warnings
warnings.simplefilter('ignore')
import mcvine
warnings.simplefilter('default')

def main():
    from mcvine.applications.InstrumentBuilder import build
    #components = ['source', 'sample', 'detector']
    components = ['source', 'monitor_source_energy', 'monitor_source_tof', 'monitor_0', 'aperture_0', 'monitor_1', 'aperture_1', 'sample', 'detector', 'neutron_printer']
    App = build(components)
    app = App('ssd')
    app.run()
    return

if __name__ == '__main__': main()

# This application was created by the following command:
# $ mcvine-create-instrument-simulation-application -name=ssd -components=source,sample,detector

