# Generated by McStasConverter, 06 Mar 2011 21:42


from vnfb.dom.neutron_experiment_simulations.neutron_components.Arm import Arm
from vnfb.dom.neutron_experiment_simulations.neutron_components.SNSModerator import SNSModerator
from vnfb.dom.neutron_experiment_simulations.neutron_components.CollimatorLinear import CollimatorLinear
from vnfb.dom.neutron_experiment_simulations.neutron_components.Slit import Slit
from vnfb.dom.neutron_experiment_simulations.neutron_components.LMonitor import LMonitor
from vnfb.dom.neutron_experiment_simulations.neutron_components.Guide import Guide
from vnfb.dom.neutron_experiment_simulations.neutron_components.DiskChopper import DiskChopper
from vnfb.dom.neutron_experiment_simulations.neutron_components.GuideGravity import GuideGravity
from vnfb.dom.neutron_experiment_simulations.neutron_components.PSDMonitor import PSDMonitor
from vnfb.dom.neutron_experiment_simulations.neutron_components.NDMonitor import NDMonitor
from vnfb.dom.neutron_experiment_simulations.neutron_components.VanadiumPlate import VanadiumPlate
from vnfb.dom.neutron_experiment_simulations.neutron_components.PSD_TEWMonitor import PSD_TEWMonitor
from vnfb.dom.neutron_experiment_simulations.neutron_components.Monitor import Monitor

from vnfb.dom.neutron_experiment_simulations.neutron_components.NeutronRecorder import NeutronRecorder

def arm():
    c = Arm()
    c.short_description = "arm"
    return c

def source():
    c = SNSModerator()
    c.short_description = "source"
    c.yh = 0.085
    c.dist = 4.3
    c.Emin = 0.01
    c.Emax = 1000
    c.tinmin = 0.0
    c.sample_t = 1
    c.height = 0.12
    c.width = 0.10
    c.proton_T = 0.600
    c.tinmax = 2000.0
    c.sample_E = 2
    c.S_filename = "a1Gw2-8-f5_fit_fit.dat"
    c.xw = 0.016
    return c

def core_vessel_insert():
    c = CollimatorLinear()
    c.short_description = "core_vessel_insert"
    c.y_max = 0.06
    c.transmission = 1
    c.divergence = 0
    c.len = 1.359
    c.x_max = 0.05
    c.x_min = -0.05
    c.y_min = -0.06
    return c

def start_shutter_insert():
    c = Slit()
    c.short_description = "start_shutter_insert"
    c.x_min = -0.025
    c.y_min = -0.045
    c.radius = 0
    c.y_max = 0.045
    c.x_max = 0.025
    return c

def end_shutter_insert():
    c = Slit()
    c.short_description = "end_shutter_insert"
    c.x_min = -0.008
    c.y_min = -0.045
    c.radius = 0
    c.y_max = 0.045
    c.x_max = 0.008
    return c

def L_monitor1():
    c = LMonitor()
    c.short_description = "L_monitor1"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor1.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def bulk_shield_insert1():
    c = Guide()
    c.short_description = "bulk_shield_insert1"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084688
    c.h1 = 0.084702
    c.m = 3.06
    c.l = 0.4965
    c.Qc = 0.0219
    c.w2 = 0.016096
    c.w1 = .014999
    c.alpha = 3.547
    return c

def bulk_shield_insert2():
    c = Guide()
    c.short_description = "bulk_shield_insert2"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084696
    c.h1 = 0.084706
    c.m = 3.09
    c.l = 0.4965
    c.Qc = 0.0219
    c.w2 = 0.016590
    c.w1 = .016090
    c.alpha = 3.277
    return c

def BS_Out():
    c = Arm()
    c.short_description = "BS_Out"
    return c

def L_monitor2():
    c = LMonitor()
    c.short_description = "L_monitor2"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor2.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def transition_guide1():
    c = Guide()
    c.short_description = "transition_guide1"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084695
    c.h1 = 0.084702
    c.m = 3.075
    c.l = 0.400
    c.Qc = 0.0219
    c.w2 = 0.016817
    c.w1 = .016594
    c.alpha = 4.841
    return c

def transition_guide2():
    c = Guide()
    c.short_description = "transition_guide2"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084689
    c.h1 = 0.084700
    c.m = 3.125
    c.l = 0.400
    c.Qc = 0.0219
    c.w2 = 0.016960
    c.w1 = .016811
    c.alpha = 4.190
    return c

def transition_guide3():
    c = Guide()
    c.short_description = "transition_guide3"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084700
    c.h1 = 0.084709
    c.m = 3.065
    c.l = 0.4079
    c.Qc = 0.0219
    c.w2 = 0.017107
    c.w1 = .016979
    c.alpha = 4.091
    return c

def TRG_Out():
    c = Arm()
    c.short_description = "TRG_Out"
    return c

def L_monitor3():
    c = LMonitor()
    c.short_description = "L_monitor3"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor3.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def bandwidth_chopper():
    c = DiskChopper()
    c.short_description = "bandwidth_chopper"
    c.t_0 = dc_tphase
    c.R = 0.25
    c.omega = dc_omega
    c.theta_0 = 49.23
    c.n = 1
    return c

def curved_guide1():
    c = Guide()
    c.short_description = "curved_guide1"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084496
    c.h1 = 0.084490
    c.m = 3.15
    c.l = 0.4953
    c.Qc = 0.0219
    c.w2 = 0.01700
    c.w1 = 0.017002
    c.alpha = 2.761
    return c

def curved_guide2():
    c = Guide()
    c.short_description = "curved_guide2"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084488
    c.h1 = 0.084487
    c.m = 3.115
    c.l = 0.4953
    c.Qc = 0.0219
    c.w2 = 0.017004
    c.w1 = 0.017002
    c.alpha = 3.130
    return c

def curved_guide3():
    c = Guide()
    c.short_description = "curved_guide3"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084484
    c.h1 = 0.084486
    c.m = 3.105
    c.l = 0.4953
    c.Qc = 0.0219
    c.w2 = 0.017000
    c.w1 = 0.017003
    c.alpha = 3.254
    return c

def curved_guide4():
    c = Guide()
    c.short_description = "curved_guide4"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084483
    c.h1 = 0.084485
    c.m = 3.105
    c.l = 0.4953
    c.Qc = 0.0219
    c.w2 = 0.017001
    c.w1 = 0.017004
    c.alpha = 3.688
    return c

def curved_guide5():
    c = Guide()
    c.short_description = "curved_guide5"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084488
    c.h1 = 0.084489
    c.m = 3.07
    c.l = 0.4953
    c.Qc = 0.0219
    c.w2 = 0.017004
    c.w1 = 0.017004
    c.alpha = 3.640
    return c

def curved_guide6():
    c = Guide()
    c.short_description = "curved_guide6"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084489
    c.h1 = 0.084483
    c.m = 3.145
    c.l = 0.4953
    c.Qc = 0.0219
    c.w2 = 0.017007
    c.w1 = 0.017004
    c.alpha = 2.874
    return c

def CG1_Out():
    c = Arm()
    c.short_description = "CG1_Out"
    return c

def L_monitor4():
    c = LMonitor()
    c.short_description = "L_monitor4"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor4.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def curved_guide7():
    c = Guide()
    c.short_description = "curved_guide7"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.174
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.795
    return c

def curved_guide8():
    c = Guide()
    c.short_description = "curved_guide8"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.174
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.795
    return c

def curved_guide9():
    c = Guide()
    c.short_description = "curved_guide9"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.174
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.795
    return c

def curved_guide10():
    c = Guide()
    c.short_description = "curved_guide10"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.174
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.795
    return c

def curved_guide11():
    c = Guide()
    c.short_description = "curved_guide11"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.147
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.829
    return c

def curved_guide12():
    c = Guide()
    c.short_description = "curved_guide12"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.147
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.829
    return c

def curved_guide13():
    c = Guide()
    c.short_description = "curved_guide13"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.147
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.829
    return c

def curved_guide14():
    c = Guide()
    c.short_description = "curved_guide14"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.147
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.829
    return c

def curved_guide15():
    c = Guide()
    c.short_description = "curved_guide15"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.130
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.494
    return c

def curved_guide16():
    c = Guide()
    c.short_description = "curved_guide16"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.130
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.494
    return c

def curved_guide17():
    c = Guide()
    c.short_description = "curved_guide17"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.130
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.494
    return c

def curved_guide18():
    c = Guide()
    c.short_description = "curved_guide18"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.130
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.494
    return c

def curved_guide19():
    c = Guide()
    c.short_description = "curved_guide19"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.153
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.245
    return c

def curved_guide20():
    c = Guide()
    c.short_description = "curved_guide20"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.153
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.245
    return c

def curved_guide21():
    c = Guide()
    c.short_description = "curved_guide21"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.153
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.245
    return c

def curved_guide22():
    c = Guide()
    c.short_description = "curved_guide22"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.153
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.245
    return c

def curved_guide23():
    c = Guide()
    c.short_description = "curved_guide23"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.166
    return c

def curved_guide24():
    c = Guide()
    c.short_description = "curved_guide24"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.166
    return c

def curved_guide25():
    c = Guide()
    c.short_description = "curved_guide25"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.166
    return c

def curved_guide26():
    c = Guide()
    c.short_description = "curved_guide26"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.166
    return c

def curved_guide27():
    c = Guide()
    c.short_description = "curved_guide27"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.041
    return c

def curved_guide28():
    c = Guide()
    c.short_description = "curved_guide28"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.041
    return c

def curved_guide29():
    c = Guide()
    c.short_description = "curved_guide29"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.041
    return c

def curved_guide30():
    c = Guide()
    c.short_description = "curved_guide30"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.207
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.041
    return c

def curved_guide31():
    c = Guide()
    c.short_description = "curved_guide31"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.143
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.132
    return c

def curved_guide32():
    c = Guide()
    c.short_description = "curved_guide32"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.143
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.132
    return c

def curved_guide33():
    c = Guide()
    c.short_description = "curved_guide33"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.143
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.132
    return c

def curved_guide34():
    c = Guide()
    c.short_description = "curved_guide34"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.143
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 3.132
    return c

def curved_guide35():
    c = Guide()
    c.short_description = "curved_guide35"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.180
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.576
    return c

def curved_guide36():
    c = Guide()
    c.short_description = "curved_guide36"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.180
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.576
    return c

def curved_guide37():
    c = Guide()
    c.short_description = "curved_guide37"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.180
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.576
    return c

def curved_guide38():
    c = Guide()
    c.short_description = "curved_guide38"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.180
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.576
    return c

def curved_guide39():
    c = Guide()
    c.short_description = "curved_guide39"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.183
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.782
    return c

def curved_guide40():
    c = Guide()
    c.short_description = "curved_guide40"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.183
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.782
    return c

def curved_guide41():
    c = Guide()
    c.short_description = "curved_guide41"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.183
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.782
    return c

def curved_guide42():
    c = Guide()
    c.short_description = "curved_guide42"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.084
    c.h1 = 0.084
    c.m = 3.183
    c.l = 0.4721
    c.Qc = 0.0219
    c.w2 = 0.017
    c.w1 = 0.017
    c.alpha = 2.782
    return c

def CG2_Out():
    c = Arm()
    c.short_description = "CG2_Out"
    return c

def L_monitor5():
    c = LMonitor()
    c.short_description = "L_monitor5"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor5.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def straight_section1():
    c = Guide()
    c.short_description = "straight_section1"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.083990
    c.h1 = 0.083988
    c.m = 3.153
    c.l = 1.7998
    c.Qc = 0.0219
    c.w2 = 0.017005
    c.w1 = .017005
    c.alpha = 3.499
    return c

def straight_section2():
    c = Guide()
    c.short_description = "straight_section2"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.083991
    c.h1 = 0.083987
    c.m = 3.140
    c.l = 1.7998
    c.Qc = 0.0219
    c.w2 = 0.017002
    c.w1 = .017007
    c.alpha = 3.201
    return c

def straight_section3():
    c = Guide()
    c.short_description = "straight_section3"
    c.R0 = 0.99
    c.W = 0.003
    c.h2 = 0.083991
    c.h1 = 0.083991
    c.m = 3.153
    c.l = 1.7998
    c.Qc = 0.0219
    c.w2 = 0.017004
    c.w1 = .017004
    c.alpha = 3.287
    return c

def SG_Out():
    c = Arm()
    c.short_description = "SG_Out"
    return c

def L_monitor6():
    c = LMonitor()
    c.short_description = "L_monitor6"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor6.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def VTG_Slit():
    c = Slit()
    c.short_description = "VTG_Slit"
    c.width = 0.017
    c.height = 0.084
    return c

def vertical_tapered_guide1():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide1"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.07
    c.h2 = 0.083943
    c.h1 = 0.083997
    c.l = 0.47983
    c.mleft = 3.07
    c.Qc = 0.0219
    c.w2 = 0.016998
    c.w1 = 0.017001
    c.alpha = 3.750
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide2():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide2"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.10
    c.h2 = 0.083769
    c.h1 = 0.08393
    c.l = 0.4800
    c.mleft = 3.10
    c.Qc = 0.0219
    c.w2 = 0.016995
    c.w1 = 0.01700
    c.alpha = 4.131
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide3():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide3"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.10
    c.h2 = 0.083499
    c.h1 = 0.083773
    c.l = 0.47987
    c.mleft = 3.10
    c.Qc = 0.0219
    c.w2 = 0.016999
    c.w1 = 0.016997
    c.alpha = 4.131
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide4():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide4"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.07
    c.h2 = 0.083090
    c.h1 = 0.083483
    c.l = 0.47483
    c.mleft = 3.07
    c.Qc = 0.0219
    c.w2 = 0.016996
    c.w1 = 0.016991
    c.alpha = 3.750
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide5():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide5"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.10
    c.h2 = 0.082584
    c.h1 = 0.083101
    c.l = 0.470
    c.mleft = 3.10
    c.Qc = 0.0219
    c.w2 = 0.016994
    c.w1 = 0.016991
    c.alpha = 3.696
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide6():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide6"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.10
    c.h2 = 0.081945
    c.h1 = 0.082572
    c.l = 0.463
    c.mleft = 3.10
    c.Qc = 0.0219
    c.w2 = 0.016999
    c.w1 = 0.016991
    c.alpha = 3.696
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide7():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide7"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.02
    c.h2 = 0.081187
    c.h1 = 0.081945
    c.l = 0.45587
    c.mleft = 3.02
    c.Qc = 0.0219
    c.w2 = 0.017002
    c.w1 = 0.017001
    c.alpha = 3.843
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide8():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide8"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.02
    c.h2 = 0.080320
    c.h1 = 0.081189
    c.l = 0.44883
    c.mleft = 3.02
    c.Qc = 0.0219
    c.w2 = 0.017001
    c.w1 = 0.017001
    c.alpha = 3.843
    c.mbottom = 3.60
    c.mtop = 3.60
    return c

def vertical_tapered_guide9():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide9"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.00
    c.h2 = 0.079289
    c.h1 = 0.080303
    c.l = 0.44200
    c.mleft = 3.00
    c.Qc = 0.0219
    c.w2 = 0.016991
    c.w1 = 0.016990
    c.alpha = 3.881
    c.mbottom = 3.70
    c.mtop = 3.70
    return c

def vertical_tapered_guide10():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide10"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.15
    c.h2 = 0.078152
    c.h1 = 0.079285
    c.l = 0.43500
    c.mleft = 3.15
    c.Qc = 0.0219
    c.w2 = 0.016997
    c.w1 = 0.016998
    c.alpha = 3.610
    c.mbottom = 3.70
    c.mtop = 3.70
    return c

def vertical_tapered_guide11():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide11"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.15
    c.h2 = 0.076860
    c.h1 = 0.078150
    c.l = 0.42787
    c.mleft = 3.15
    c.Qc = 0.0219
    c.w2 = 0.017002
    c.w1 = 0.016998
    c.alpha = 4.035
    c.mbottom = 3.65
    c.mtop = 3.65
    return c

def vertical_tapered_guide12():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide12"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.15
    c.h2 = 0.075431
    c.h1 = 0.076851
    c.l = 0.42083
    c.mleft = 3.15
    c.Qc = 0.0219
    c.w2 = 0.016998
    c.w1 = 0.017001
    c.alpha = 4.035
    c.mbottom = 3.70
    c.mtop = 3.70
    return c

def vertical_tapered_guide13():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide13"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.10
    c.h2 = 0.073850
    c.h1 = 0.075419
    c.l = 0.41400
    c.mleft = 3.10
    c.Qc = 0.0219
    c.w2 = 0.017002
    c.w1 = 0.017000
    c.alpha = 3.914
    c.mbottom = 3.65
    c.mtop = 3.65
    return c

def vertical_tapered_guide14():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide14"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.15
    c.h2 = 0.072128
    c.h1 = 0.073851
    c.l = 0.40700
    c.mleft = 3.15
    c.Qc = 0.0219
    c.w2 = 0.016999
    c.w1 = 0.016991
    c.alpha = 4.035
    c.mbottom = 3.65
    c.mtop = 3.65
    return c

def vertical_tapered_guide15():
    c = GuideGravity()
    c.short_description = "vertical_tapered_guide15"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = 3.15
    c.h2 = 0.070227
    c.h1 = 0.072125
    c.l = 0.39752
    c.mleft = 3.15
    c.Qc = 0.0219
    c.w2 = 0.017001
    c.w1 = 0.0169981
    c.alpha = 3.823
    c.mbottom = 3.65
    c.mtop = 3.65
    return c

def VTG_Out():
    c = Arm()
    c.short_description = "VTG_Out"
    return c

def L_monitor7():
    c = LMonitor()
    c.short_description = "L_monitor7"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor7.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def TG_Slit():
    c = Slit()
    c.short_description = "TG_Slit"
    c.width = tg_w11
    c.height = 0.0686
    return c

def tapered_guide1():
    c = GuideGravity()
    c.short_description = "tapered_guide1"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid1
    c.h2 = tg_h21
    c.h1 = tg_h11
    c.l = 0.39845
    c.mleft = tg_m_sid1
    c.Qc = 0.0219
    c.w2 = tg_w21
    c.w1 = tg_w11
    c.alpha = tg_alpha1
    c.mbottom = tg_m_top1
    c.mtop = tg_m_top1
    return c

def tapered_guide2():
    c = GuideGravity()
    c.short_description = "tapered_guide2"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid2
    c.h2 = tg_h22
    c.h1 = tg_h12
    c.l = 0.40000
    c.mleft = tg_m_sid2
    c.Qc = 0.0219
    c.w2 = tg_w22
    c.w1 = tg_w12
    c.alpha = tg_alpha2
    c.mbottom = tg_m_top2
    c.mtop = tg_m_top2
    return c

def tapered_guide3():
    c = GuideGravity()
    c.short_description = "tapered_guide3"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid3
    c.h2 = tg_h23
    c.h1 = tg_h13
    c.l = 0.40000
    c.mleft = tg_m_sid3
    c.Qc = 0.0219
    c.w2 = tg_w23
    c.w1 = tg_w13
    c.alpha = tg_alpha3
    c.mbottom = tg_m_top3
    c.mtop = tg_m_top3
    return c

def tapered_guide4():
    c = GuideGravity()
    c.short_description = "tapered_guide4"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid4
    c.h2 = tg_h24
    c.h1 = tg_h14
    c.l = 0.39990
    c.mleft = tg_m_sid4
    c.Qc = 0.0219
    c.w2 = tg_w24
    c.w1 = tg_w14
    c.alpha = tg_alpha4
    c.mbottom = tg_m_top4
    c.mtop = tg_m_top4
    return c

def tapered_guide5():
    c = GuideGravity()
    c.short_description = "tapered_guide5"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid5
    c.h2 = tg_h25
    c.h1 = tg_h15
    c.l = 0.37988
    c.mleft = tg_m_sid5
    c.Qc = 0.0219
    c.w2 = tg_w25
    c.w1 = tg_w15
    c.alpha = tg_alpha5
    c.mbottom = tg_m_top5
    c.mtop = tg_m_top5
    return c

def tapered_guide6():
    c = GuideGravity()
    c.short_description = "tapered_guide6"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid6
    c.h2 = tg_h26
    c.h1 = tg_h16
    c.l = 0.36000
    c.mleft = tg_m_sid6
    c.Qc = 0.0219
    c.w2 = tg_w26
    c.w1 = tg_w16
    c.alpha = tg_alpha6
    c.mbottom = tg_m_top6
    c.mtop = tg_m_top6
    return c

def tapered_guide7():
    c = GuideGravity()
    c.short_description = "tapered_guide7"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid7
    c.h2 = tg_h27
    c.h1 = tg_h17
    c.l = 0.33000
    c.mleft = tg_m_sid7
    c.Qc = 0.0219
    c.w2 = tg_w27
    c.w1 = tg_w17
    c.alpha = tg_alpha7
    c.mbottom = tg_m_top7
    c.mtop = tg_m_top7
    return c

def tapered_guide8():
    c = GuideGravity()
    c.short_description = "tapered_guide8"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid8
    c.h2 = tg_h28
    c.h1 = tg_h18
    c.l = 0.29000
    c.mleft = tg_m_sid8
    c.Qc = 0.0219
    c.w2 = tg_w28
    c.w1 = tg_w18
    c.alpha = tg_alpha8
    c.mbottom = tg_m_top8
    c.mtop = tg_m_top8
    return c

def tapered_guide9():
    c = GuideGravity()
    c.short_description = "tapered_guide9"
    c.R0 = 0.99
    c.W = 0.003
    c.G = 0
    c.mright = tg_m_sid9
    c.h2 = tg_h29
    c.h1 = tg_h19
    c.l = 0.23848
    c.mleft = tg_m_sid9
    c.Qc = 0.0219
    c.w2 = tg_w29
    c.w1 = tg_w19
    c.alpha = tg_alpha9
    c.mbottom = tg_m_top9
    c.mtop = tg_m_top9
    return c

def TG_Out():
    c = Arm()
    c.short_description = "TG_Out"
    return c

def L_monitor8():
    c = LMonitor()
    c.short_description = "L_monitor8"
    c.nchan = 140
    c.y_height = 0.1
    c.filename = "Vulcan_asbuilt_L_monitor8.txt"
    c.Lmax = 14.0
    c.x_width = 0.1
    c.Lmin = 0.0
    return c

def FU_Out():
    c = Arm()
    c.short_description = "FU_Out"
    return c

def L_monitor9():
    c = LMonitor()
    c.short_description = "L_monitor9"
    c.nchan = 140
    c.y_height = 0.15
    c.restore_neutron = 1
    c.filename = "Vulcan_asbuilt_L_monitor9.txt"
    c.Lmax = 14.0
    c.x_width = 0.15
    c.Lmin = 0.0
    return c

def L_monitor10():
    c = LMonitor()
    c.short_description = "L_monitor10"
    c.nchan = 140
    c.y_height = 0.002
    c.restore_neutron = 1
    c.filename = "Vulcan_asbuilt_L_monitor10.txt"
    c.Lmax = 14.0
    c.x_width = 0.002
    c.Lmin = 0.0
    return c

def psd_sample_position():
    c = PSDMonitor()
    c.short_description = "psd_sample_position"
    c.y_height = 0.1
    c.restore_neutron = 1
    c.filename = "Vulcan_asbuilt_sample_psd.txt"
    c.nx = 50
    c.ny = 50
    c.x_width = 0.05
    return c

#def psd_xscan_L():
#    c = NDMonitor()
#    c.short_description = "psd_xscan_L"
#    c.x_width = 0.1
#    c.y_height = 0.1
#    c.options = "square, wavelength limits=[0.875 3.025] bins=21 x limits=[-0.03 0.03] bins=60, file=Vulcan_asbuilt_xscan.txt"
#    return c
#
#def psd_yscan_L():
#    c = NDMonitor()
#    c.short_description = "psd_yscan_L"
#    c.x_width = 0.1
#    c.y_height = 0.1
#    c.options = "square, wavelength limits=[0.875 3.025] bins=21 y limits=[-0.05 0.05] bins=100, file=Vulcan_asbuilt_yscan.txt"
#    return c
#
#def sample():
#    c = VanadiumPlate()
#    c.short_description = "sample"
#    c.focus_yh = 1.30
#    c.h = 0.05
#    c.target_z = 0
#    c.target_x = -2
#    c.target_y = 0
#    c.focus_xw = 0.780
#    c.frac = 1
#    c.radius_i = 0.015
#    c.radius_o = 0.02
#    c.pack = 1
#    return c
#
#def Detector_Position_c():
#    c = Arm()
#    c.short_description = "Detector_Position_c"
#    return c
#
#def detector_90tc():
#    c = PSD_TEWMonitor()
#    c.short_description = "detector_90tc"
#    c.nxchan = 1
#    c.format = out_format
#    c.bmax = 100
#    c.y_height = 0.385
#    c.restore_neutron = 1
#    c.filename = "Vulcan_asbuilt_Ldetector_l90tc.txt"
#    c.nychan = 1
#    c.bmin = 0
#    c.nbchan = 100
#    c.x_width = 0.770
#    c.type = "time"
#    return c
#
#def detector_90wc():
#    c = PSD_TEWMonitor()
#    c.short_description = "detector_90wc"
#    c.nxchan = 1
#    c.format = out_format
#    c.bmax = 10
#    c.y_height = 0.385
#    c.restore_neutron = 1
#    c.filename = "Vulcan_asbuilt_Ldetector_l90wc.txt"
#    c.nychan = 1
#    c.bmin = 0
#    c.nbchan = 100
#    c.x_width = 0.770
#    c.type = "wavelength"
#    return c
#
#def Detector_Position_t():
#    c = Arm()
#    c.short_description = "Detector_Position_t"
#    return c
#
#def Detector_Position_tt():
#    c = Arm()
#    c.short_description = "Detector_Position_tt"
#    return c
#
#def detector_90tt():
#    c = PSD_TEWMonitor()
#    c.short_description = "detector_90tt"
#    c.nxchan = 1
#    c.format = out_format
#    c.bmax = 100
#    c.y_height = 0.385
#    c.restore_neutron = 1
#    c.filename = "Vulcan_asbuilt_Ldetector_l90tt.txt"
#    c.nychan = 1
#    c.bmin = 0
#    c.nbchan = 100
#    c.x_width = 0.770
#    c.type = "time"
#    return c
#
#def detector_90wt():
#    c = PSD_TEWMonitor()
#    c.short_description = "detector_90wt"
#    c.nxchan = 1
#    c.format = out_format
#    c.bmax = 10
#    c.y_height = 0.385
#    c.restore_neutron = 1
#    c.filename = "Vulcan_asbuilt_Ldetector_l90wt.txt"
#    c.nychan = 1
#    c.bmin = 0
#    c.nbchan = 100
#    c.x_width = 0.770
#    c.type = "wavelength"
#    return c
#
#def Detector_Position_b():
#    c = Arm()
#    c.short_description = "Detector_Position_b"
#    return c
#
#def Detector_Position_bb():
#    c = Arm()
#    c.short_description = "Detector_Position_bb"
#    return c
#
#def detector_90tb():
#    c = PSD_TEWMonitor()
#    c.short_description = "detector_90tb"
#    c.nxchan = 1
#    c.format = out_format
#    c.bmax = 100
#    c.y_height = 0.385
#    c.restore_neutron = 1
#    c.filename = "Vulcan_asbuilt_Ldetector_l90tb.txt"
#    c.nychan = 1
#    c.bmin = 0
#    c.nbchan = 100
#    c.x_width = 0.770
#    c.type = "time"
#    return c
#
#def detector_90wb():
#    c = PSD_TEWMonitor()
#    c.short_description = "detector_90wb"
#    c.nxchan = 1
#    c.format = out_format
#    c.bmax = 10
#    c.y_height = 0.385
#    c.restore_neutron = 1
#    c.filename = "Vulcan_asbuilt_Ldetector_l90wb.txt"
#    c.nychan = 1
#    c.bmin = 0
#    c.nbchan = 100
#    c.x_width = 0.770
#    c.type = "wavelength"
#    return c
#
#def monitor_beamstop():
#    c = Monitor()
#    c.short_description = "monitor_beamstop"
#    c.x_min = -1
#    c.y_min = -1
#    c.y_max = 1
#    c.x_max = 1
#    return c


def neutron_recorder():
    c = NeutronRecorder()
    c.short_description = "Neutron recorder at sample position"
    return c

from _utils import ccomp, cinstr

def createInstrument(director):
    components = [
        ccomp("arm", arm(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), '')),
        ccomp("source", source(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), '')),
        ccomp("core_vessel_insert", core_vessel_insert(), ((0.00000, 0.00000, 1.02000), (0.00000, 0.00000, 0.00000), '')),
        ccomp("start_shutter_insert", start_shutter_insert(), ((0.00000, 0.00000, 2.40100), (0.00000, 0.00000, 0.00000), '')),
        ccomp("end_shutter_insert", end_shutter_insert(), ((0.00000, 0.00000, 4.26800), (0.00000, 0.00000, 0.00000), '')),
        ccomp("L_monitor1", L_monitor1(), ((0.00000, 0.00000, 4.30000), (0.00000, 0.00000, 0.00000), '')),
        ccomp("bulk_shield_insert1", bulk_shield_insert1(), ((0.00000, 0.00000, 4.30330), (0.00000, 0.00000, 0.00000), '')),
        ccomp("bulk_shield_insert2", bulk_shield_insert2(), ((0.00000, 0.00000, 0.49750), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("BS_Out", BS_Out(), ((0.00000, 0.00000, 0.49750), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor2", L_monitor2(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("transition_guide1", transition_guide1(), ((0.00000, 0.00000, 0.00614), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("transition_guide2", transition_guide2(), ((0.00000, 0.00000, 0.40010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("transition_guide3", transition_guide3(), ((0.00000, 0.00000, 0.40010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("TRG_Out", TRG_Out(), ((0.00000, 0.00000, 0.40800), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor3", L_monitor3(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("bandwidth_chopper", bandwidth_chopper(), ((0.00000, 0.00000, 0.09000), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("curved_guide1", curved_guide1(), ((0.00000, 0.00000, 0.09353), (0.00000, 0.01015, 0.00000), 'previous')),
        ccomp("curved_guide2", curved_guide2(), ((0.00000, 0.00000, 0.49540), (0.00000, 0.01015, 0.00000), 'curved_guide1')),
        ccomp("curved_guide3", curved_guide3(), ((0.00000, 0.00000, 0.49540), (0.00000, 0.01015, 0.00000), 'curved_guide2')),
        ccomp("curved_guide4", curved_guide4(), ((0.00000, 0.00000, 0.49540), (0.00000, 0.01015, 0.00000), 'curved_guide3')),
        ccomp("curved_guide5", curved_guide5(), ((0.00000, 0.00000, 0.49540), (0.00000, 0.01015, 0.00000), 'curved_guide4')),
        ccomp("curved_guide6", curved_guide6(), ((0.00000, 0.00000, 0.49540), (0.00000, 0.01015, 0.00000), 'curved_guide5')),
        ccomp("CG1_Out", CG1_Out(), ((0.00000, 0.00000, 0.49540), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor4", L_monitor4(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("curved_guide7", curved_guide7(), ((0.00000, 0.00000, 0.09512), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide8", curved_guide8(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide9", curved_guide9(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide10", curved_guide10(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide11", curved_guide11(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide12", curved_guide12(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide13", curved_guide13(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide14", curved_guide14(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide15", curved_guide15(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide16", curved_guide16(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide17", curved_guide17(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide18", curved_guide18(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide19", curved_guide19(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide20", curved_guide20(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide21", curved_guide21(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide22", curved_guide22(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide23", curved_guide23(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide24", curved_guide24(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide25", curved_guide25(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide26", curved_guide26(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide27", curved_guide27(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide28", curved_guide28(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide29", curved_guide29(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide30", curved_guide30(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide31", curved_guide31(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide32", curved_guide32(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide33", curved_guide33(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide34", curved_guide34(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide35", curved_guide35(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide36", curved_guide36(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide37", curved_guide37(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide38", curved_guide38(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide39", curved_guide39(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide40", curved_guide40(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide41", curved_guide41(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("curved_guide42", curved_guide42(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("CG2_Out", CG2_Out(), ((0.00000, 0.00000, 0.47220), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor5", L_monitor5(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("straight_section1", straight_section1(), ((0.00000, 0.00000, 0.00020), (0.00000, 0.00970, 0.00000), 'previous')),
        ccomp("straight_section2", straight_section2(), ((0.00000, 0.00000, 1.80004), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("straight_section3", straight_section3(), ((0.00000, 0.00000, 1.80013), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("SG_Out", SG_Out(), ((0.00000, 0.00000, 1.80007), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor6", L_monitor6(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("VTG_Slit", VTG_Slit(), ((0.00000, 0.00000, 0.00030), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide1", vertical_tapered_guide1(), ((0.00000, 0.00000, 0.00040), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide2", vertical_tapered_guide2(), ((0.00000, 0.00000, 0.47993), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide3", vertical_tapered_guide3(), ((0.00000, 0.00000, 0.48010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide4", vertical_tapered_guide4(), ((0.00000, 0.00000, 0.48025), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide5", vertical_tapered_guide5(), ((0.00000, 0.00000, 0.47493), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide6", vertical_tapered_guide6(), ((0.00000, 0.00000, 0.47010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide7", vertical_tapered_guide7(), ((0.00000, 0.00000, 0.46310), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide8", vertical_tapered_guide8(), ((0.00000, 0.00000, 0.45629), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide9", vertical_tapered_guide9(), ((0.00000, 0.00000, 0.44893), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide10", vertical_tapered_guide10(), ((0.00000, 0.00000, 0.44210), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide11", vertical_tapered_guide11(), ((0.00000, 0.00000, 0.43510), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide12", vertical_tapered_guide12(), ((0.00000, 0.00000, 0.42828), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide13", vertical_tapered_guide13(), ((0.00000, 0.00000, 0.42093), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide14", vertical_tapered_guide14(), ((0.00000, 0.00000, 0.41410), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("vertical_tapered_guide15", vertical_tapered_guide15(), ((0.00000, 0.00000, 0.40710), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("VTG_Out", VTG_Out(), ((0.00000, 0.00000, 0.39762), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor7", L_monitor7(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("TG_Slit", TG_Slit(), ((0.00000, 0.00000, 0.15906), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide1", tapered_guide1(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'TG_Slit')),
        ccomp("tapered_guide2", tapered_guide2(), ((0.00000, 0.00000, 0.39855), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide3", tapered_guide3(), ((0.00000, 0.00000, 0.40010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide4", tapered_guide4(), ((0.00000, 0.00000, 0.40010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide5", tapered_guide5(), ((0.00000, 0.00000, 0.40000), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide6", tapered_guide6(), ((0.00000, 0.00000, 0.37998), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide7", tapered_guide7(), ((0.00000, 0.00000, 0.36010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide8", tapered_guide8(), ((0.00000, 0.00000, 0.33010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("tapered_guide9", tapered_guide9(), ((0.00000, 0.00000, 0.29010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("TG_Out", TG_Out(), ((0.00000, 0.00000, 0.23858), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor8", L_monitor8(), ((0.00000, 0.00000, 0.00010), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("FU_Out", FU_Out(), ((0.00000, 0.00000, 0.63240), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor9", L_monitor9(), ((0.00000, 0.00000, 0.97100), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("L_monitor10", L_monitor10(), ((0.00000, 0.00000, 0.97200), (0.00000, 0.00000, 0.00000), 'previous')),
        ccomp("psd_sample_position", psd_sample_position(), ((0.00000, 0.00000, 0.97300), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("psd_xscan_L", psd_xscan_L(), ((0.00000, 0.00000, 0.97400), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("psd_yscan_L", psd_yscan_L(), ((0.00000, 0.00000, 0.97500), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("sample", sample(), ((0.00000, 0.00000, 1.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("Detector_Position_c", Detector_Position_c(), ((-2.00000, 0.00000, 0.00000), (0.00000, 90.00000, 0.00000), 'sample')),
#        ccomp("detector_90tc", detector_90tc(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("detector_90wc", detector_90wc(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("Detector_Position_t", Detector_Position_t(), ((-1.95900, 0.40300, 0.00000), (0.00000, 90.00000, 0.00000), 'sample')),
#        ccomp("Detector_Position_tt", Detector_Position_tt(), ((0.00000, 0.00000, 0.00000), (11.60000, 0.00000, 0.00000), 'previous')),
#        ccomp("detector_90tt", detector_90tt(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("detector_90wt", detector_90wt(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("Detector_Position_b", Detector_Position_b(), ((-1.95900, -0.40300, 0.00000), (0.00000, 90.00000, 0.00000), 'sample')),
#        ccomp("Detector_Position_bb", Detector_Position_bb(), ((0.00000, 0.00000, 0.00000), (-11.60000, 0.00000, 0.00000), 'previous')),
#        ccomp("detector_90tb", detector_90tb(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("detector_90wb", detector_90wb(), ((0.00000, 0.00000, 0.00000), (0.00000, 0.00000, 0.00000), 'previous')),
#        ccomp("monitor_beamstop", monitor_beamstop(), ((0.00000, 0.00000, 5.00000), (0.00000, 0.00000, 0.00000), 'sample')),
        ]


    instrument = cinstr(
        director,
        name = "",
        short_description = "",
        long_description = "",
        category = "",
        creator = "VNF",
        date = "06 Mar 2011 21:42",
        components = components
        )


