#!/usr/bin/env python

cmd_help = """
Simulate SEQUOIA beam.

It is a wrapper of sequoia-m2s and convenient tools to 
compute monitor spectra and others.

Example:

 $ sequoia_beam --fermi_chopper=1 --fermi_nu=600 --T0_nu=60 --E=600 --ncount=1e8

For more details of cmd line parameters, run:

 $ sequoia_beam --help-properties

"""

# distance from moderator to monitor1, unit meter
# this should match the monitor 1 position in sequoia-moderator2sample
# application.
LM1 = 18.26
# distance from moderator to monitor2
LM2 = 29.0032
# distance to sample
LSAMPLE = 20.0254


import os, time

from pyre.applications.Script import Script as base
class App(base):

    class Inventory(base.Inventory):

        import pyre.inventory

        fermi_chopper = pyre.inventory.str(
            'fermi_chopper', default='100-2.03-AST')
        fermi_chopper.meta['tip'] = 'The choice of fermi chopper'
        fermi_chopper.validator = pyre.inventory.choice(
            ['100-2.03-AST', '700-3.56-AST',
             '700-0.5-AST', # from ARCS
             ]
            )
        
        fermi_nu = pyre.inventory.float('fermi_nu', default=600)
        fermi_nu.meta['tip'] = 'Spinning frequency of fermi chopper'
        
        T0_nu = pyre.inventory.float('T0_nu', default=60)
        T0_nu.meta['tip'] = 'Spinning frequency of T0 chopper'
        
        E = pyre.inventory.float('E', default=70)
        E.meta['tip'] = 'desired incident beam energy. unit: meV'

        emission_time = pyre.inventory.float('emission_time', default=-1)
        emission_time.meta['tip'] = 'emission time for moderator unit (microsecond)'

        ncount = pyre.inventory.float('ncount', default=1000000)


    m2sout = '_m2sout'
    out = 'out'


    def help(self):
        print cmd_help
    

    def main(self):
        if not os.path.exists(self.out):
            os.makedirs(self.out)
            
        # create configuration for sequoia moderator to sample simulation
        self._run_sequoia_m2s()
        # run the simulation from mod to sample
        self._run_beam()
        # compute flux at sample position and make sure flux is nonzero
        flux = self._computeFlux()
        # computed spectra for real monitors
        self._computeFocusedSpectraForRealMonitors()
        # simulate spectra for fake monitors at sample position
        self._runMonitorsAtSample()
        # move neutrons to output dir
        self._moveNeutronsToOutputDir()
        # compute average incident energy at sample
        energy = self._computeAverageEnergy()
        # compute fwhm of energy spetrum at sample
        fwhm = self._computeFWHM()
        fwhm *= 1e6 # convert to microsecond
        props = {
            'flux': '%s counts per 34kJ pulse' % flux,
            'average energy': '%s meV' % energy,
            'tof fwhm': '%s microsecond' % fwhm,
            }
        open(os.path.join(self.out, 'props.json'), 'w').write(str(props))
        return


    def _computeFlux(self):
        f = os.path.join(self.m2sout, 'neutrons')
        from mcni.neutron_storage.idf_usenumpy import totalintensity, count
        I = totalintensity(f)
        if I == 0:
            raise RuntimeError, "There is no neutrons at sample position. Please increase ncount"
        # one MC run corresponds to 34kJ/pulse
        # this is the flux if the power is at 34kJ/pulse
        # unit: 1/34kJ pulse
        # every neutron in the storage represents one 34kJ pulse. so 
        # we need to normalize by number of events in the storage
        nevts = count(f)
        flux = I/nevts
        return flux
    
    
    def _computeAverageEnergy(self):
        from histogram.hdf import load
        h = load(os.path.join(self.out, 'ienergy.h5'), 'ienergy')
        e = (h.energy * h.I).sum()/h.I.sum()
        return e


    def _computeFWHM(self):
        from histogram.hdf import load
        import numpy as np
        itof = load(os.path.join(self.out, 'itof.h5'), 'itof')
        max = itof.I.max()
        indmax = np.where(itof.I==max)[0][0]
        left = itof.I[:indmax]
        right = itof.I[indmax:]
        leftindex = np.where(left > max/2)[0][0]
        rightindex = np.where(right > max/2)[0][-1] + indmax
        fwhm = (rightindex-leftindex) * (itof.tof[1]-itof.tof[0])
        return fwhm


    def _moveNeutronsToOutputDir(self):
        os.rename(
            os.path.join(self.m2sout, 'neutrons'),
            os.path.join(self.out, 'neutrons'),
            )
        return


    def _runMonitorsAtSample(self):
        E = self.inventory.E
        from mcni.utils.conversion import e2v
        v = e2v(E)
        from pyre.units.time import second
        t = LSAMPLE/v

        neutronfile = os.path.join(self.m2sout, 'neutrons')
        from mcni.neutron_storage.idf_usenumpy import count
        n = count(neutronfile)

        cmd = ['sequoia_analyze_beam']
        cmd += ['--output-dir=%s' % self.out]
        cmd += ['--ncount=%s' % n]
        cmd += ['--buffer_size=%s' % min(n, 1e6)]
        cmd += ['--source.path=%s' % neutronfile]
        # fix monitor params that depend on incident energy
        cmd += ['--monitor.mtof.tofmin=%s' % (t*0.9)]
        cmd += ['--monitor.mtof.tofmax=%s' % (t*1.1)]
        cmd += ['--monitor.mtof.ntof=%s' % (1000)]
        cmd += ['--monitor.menergy.energymin=%s' % (E*0.9)]
        cmd += ['--monitor.menergy.energymax=%s' % (E*1.1)]
        cmd += ['--monitor.menergy.nenergy=%s' % (1000)]
        cmd = ' '.join(cmd)
        print 'Running beam monitors...'
        self._exec(cmd)
        print 'done.'
        time.sleep(1)
        return


    def _computeFocusedSpectraForRealMonitors(self):
        E = self.inventory.E
        from mcni.utils.conversion import e2v
        v = e2v(E)
        from pyre.units.time import second
        import histogram.hdf as hh, histogram as H
        
        m1 = hh.load(os.path.join(self.m2sout, 'mon1-tof.h5'), 'I(tof)')
        t1 = LM1/v #* second
        m1p = m1[(t1*0.9, t1*1.1)]
        m1pc = H.histogram('I(tof)', m1p.axes(), data=m1p.I, errors=m1p.E2)
        m1pc.setAttribute('title', 'Monitor 1 I(tof)')

        hh.dump(m1pc, os.path.join(self.out, 'mon1-itof-focused.h5'), '/', 'c')

        m2 = hh.load(os.path.join(self.m2sout, 'mon2-tof.h5'), 'I(tof)')
        t2 = LM2/v #* second
        m2p = m2[(t2*0.9, t2*1.1)]
        m2pc = H.histogram('I(tof)', m2p.axes(), data=m2p.I, errors=m2p.E2)
        m2pc.setAttribute('title', 'Monitor 2 I(tof)')

        hh.dump(m2pc, os.path.join(self.out, 'mon2-itof-focused.h5'), '/', 'c')
        return

    
    def _run_sequoia_m2s(self):
        cmd = ['sequoia-m2s']
        keys = [
            'fermi_chopper',
            'fermi_nu',
            'T0_nu',
            'E',
            'emission_time',
            ]
        cmd += self._buildCmdFromInventory(keys)
        cmd += ['--- -dump-pml=yes', '-h'] # , '>sequoia-m2s.log']
        cmd = ' '.join(cmd)
        print 'Generating pml for sequoia beam instrument...'
        self._exec(cmd)
        print 'done.'
        time.sleep(1)
        return


    def _run_beam(self):
        cmd = ['sequoia-moderator2sample']
        keys = ['ncount']
        cmd += self._buildCmdFromInventory(keys)
        cmd += ['-buffer_size=%s' % int(self.inventory.ncount/10)]
        cmd.append( '--output-dir=%s' % self.m2sout)
        moddat = os.path.join(
            os.environ['MCVINE_DIR'], 'share', 'mcvine',
            'instruments', 'SEQUOIA', 'source_sct521_bu_17_1.dat',
            )
        cmd += ['-mod.S_filename=%s' % moddat]
        cmd = ' '.join(cmd)
        self._exec(cmd)
        return


    def _buildCmdFromInventory(self, keys):
        kwds = {}
        for k in keys:
            v = getattr(self.inventory, k)
            kwds[k] = v
            continue
        return ['-%s=%s' % (k,v) for k,v in kwds.iteritems()]
    
    
    def _exec(self, cmd):
        print " -> running %s..." % cmd
        import os
        if os.system(cmd):
            raise RuntimeError, "%s failed" % cmd

        
def main():
    app = App('sequoia_beam')
    app.run()
    return

if __name__ == '__main__': main()
