#!/usr/bin/env python


appname = 'sequoia-nxs-populate-Eidata'
cmd_help = """
populate data reelated to Ei computation
from mod2sample simulation folder
to simulated SEQUOIA nxs file.

Examples:

 $ sequoia-nxs-populate-Eidata --mod2sample=mod2sample-out-dir --nxs=sequoia-sim.nxs

"""
__doc__ = cmd_help


# application 
from pyre.applications.Script import Script as AppBase
class App(AppBase):

    class Inventory(AppBase.Inventory):

        import pyre.inventory
        mod2sample = pyre.inventory.str('mod2sample', default='mod2sample')
        nxs = pyre.inventory.str('nxs', default='sequoia-sim.nxs')
        
        
    def main(self):
        sim_out = self.inventory.mod2sample
        f = self._nxs_file()
        entry = f['entry']
        from mcvine.instruments.SEQUOIA.nxs.raw import populateEiData
        populateEiData(entry, sim_out)
        return
    
    
    def _nxs_file(self):
        import h5py
        return h5py.File(self.inventory.nxs, 'a')


    def help(self):
        print cmd_help
    

def main():
    app = App(appname)
    app.run()
    return


if __name__ == '__main__': main()
