#!/usr/bin/env python
import warnings
warnings.simplefilter('ignore')
import mcvine
warnings.simplefilter('default')

# import journal
# journal.error("pyre.inventory").activate()

def main():
    from mcvine.instruments.SEQUOIA.Instrument import Instrument
    app = Instrument('sequoia-moderator2sample')
    app.run()
    return

if __name__ == '__main__': main()



