#!/usr/bin/env python

def run(filename):
    from mccomponents.detector import event_utils 
    evts = event_utils.readEvents(filename)
    print evts
    return


def main():
    import sys
    filename = sys.argv[1]
    run(filename)
    return


if __name__ == '__main__': main()
