#!/usr/bin/env sh


# this script runs a little test to process neutrons
# in scattered-neutrons-example
# there are 1000 neutrons.
# there should be 337 neutrons intercepted.

rm -rf out

./sd --ncount=1000 --buffer_size=1000 --source.path=scattered-neutrons-example --output-dir=out 

