#!/usr/bin/env bash
echo "Running builders/build.sh"
if [ $# -eq 0 ]
then
    echo "Usage: ./builders/build <src-path> <build-path> <install-path> <resources-path> [cores]"
    echo
    echo "Example: ./builders/build \$PWD \$PWD/build \$PWD/install \$PWD/resources 20"
    echo
    exit 1
fi

SRC=$1
BUILD=$2
INSTALL=$3
export MCVINE_RESOURCES=$4

CORES=$5
if ((CORES < 1)); then
    let CORES=`grep -c ^processor /proc/cpuinfo`
    let CORES-=1
    if ((CORES < 1)); then
	CORES = 1;
    fi
fi

echo "Building mcvine"
echo "- mcvine resoureces: $MCVINE_RESOURCES"
echo "- using $CORES cores"

# This should be in .dev-mcvine if it is needed
# . /opt/danse/bin/setup-danse.sh

rm -rf $BUILD
mkdir $BUILD
cd $BUILD
cmake $SRC \
    -DCMAKE_INSTALL_PREFIX=$INSTALL \
    -DDEPLOYMENT_PREFIX=${DEPLOYMENT_PREFIX} \
    -DPYTHON_LIBRARY=${PYTHON_LIBRARY} \
    -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} \
    -DCONDA_NO_PLUGINS=TRUE \
    && make -j$CORES reconfigure-to-include-mcstas-components \
    && make -j$CORES wrap-mcstas-components-cmake \
    && make -j$CORES 
