#!/usr/bin/env bash

if [ $# -eq 0 ]
then
    echo "Usage: ./builders/test <build-path> <resources-path> [cores] [additonal-args]"
    echo
    echo "Example: ./builders/test \$PWD/build \$PWD/resources 20 -V"
    echo
    exit 1
fi

BUILD=$1
export MCVINE_RESOURCES=$2

CORES=$3
if ((CORES < 1)); then
    let CORES=`grep -c ^processor /proc/cpuinfo`
    let CORES-=1
    if ((CORES < 1)); then
	CORES = 1;
    fi
fi

ADDI_ARGS=$4

echo "Testing mcvine"
echo "- mcvine resoureces: $MCVINE_RESOURCES"
echo "- using $CORES cores"

. /opt/danse/bin/setup-danse.sh

cd $BUILD
make test ARGS="-j$CORES $ADDI_ARGS"
