{% set version = environ.get('MCVINE_CONDA_PKG_VER', '0.0.0') %}
{% set git_revision = environ.get('GIT_FULL_HASH', '0.0.0') %}

package:
  name: mcvine-core
  version: {{ version }}

source:
  git_rev: {{ git_revision }}
  git_url: https://github.com/mcvine/mcvine.git

requirements:
  build:
    - {{ compiler('cxx') }} 7 # [linux]
    - cmake
    - libgcc                   {{ libgcc }}
  host:
    - python                   {{ python }}
    - pyyaml
    - numpy                    {{ numpy }}
    - psutil
    - h5py
    - mpi4py                  
    - openmpi                  {{ openmpi }}                      
    - libgcc                   {{ libgcc }}
    - gsl                      {{ gsl }}
    - boost                    {{ boost }}
    - mcpl
    - pyre                     {{ pyre }}
    - danse.ins.dsm
    - danse.ins.numpyext       {{ numpyext }}
    - danse.ins.bpext          {{ bpext }}
    - histogram                {{ histogram }}
    - diffpy.Structure         {{ structure }}
    - periodictable
    - mcvine-resources

  run:
    - {{ compiler('cxx') }} 7 # [linux]
    - cmake
    - libgcc                   {{ libgcc }}
    - python                   {{ python }}
    - pyyaml
    - numpy                    {{ numpy }}
    - psutil
    - h5py
    - mpi4py                   
    - openmpi                  {{ openmpi }}                      
    - gsl                      {{ gsl }}
    - boost                    {{ boost }}
    - mcpl
    - pyre                     {{ pyre }}
    - danse.ins.dsm
    - danse.ins.numpyext       {{ numpyext }}
    - danse.ins.bpext          {{ bpext }}
    - histogram                {{ histogram }}
    - diffpy.Structure         {{ structure }}
    - periodictable
    - mcvine-resources
    - phonopy
    - scipy
    - matplotlib

build:
  script_env:
    - CORES

test:
  imports:
    - mcvine
  
about:
  home: http://mcvine.org
  license:
  license_file:
