#!/usr/bin/env python


appname = 'hyspec-nxs-populate-Eidata'
cmd_help = """
populate metadata to simulated HYSPEC nxs file
using inputs such as beam simulation output directory,
sample angle, and detector vessel angle

Examples:

 $ hyspec-nxs-populate-metadata --mod2sample=mod2sample-out-dir --sample=30 --detector=45 --nxs=hyspec-sim.nxs

"""
__doc__ = cmd_help


# application 
from pyre.applications.Script import Script as AppBase
class App(AppBase):

    class Inventory(AppBase.Inventory):

        import pyre.inventory
        mod2sample = pyre.inventory.str('mod2sample', default='mod2sample')
        nxs = pyre.inventory.str('nxs', default='hyspec-sim.nxs')
        sample = pyre.inventory.float('sample', default=0)
        detector = pyre.inventory.float('detector', default=45)
        
        
    def main(self):
        sim_out = self.inventory.mod2sample
        sample = self.inventory.sample
        detector = self.inventory.detector
        f = self._nxs_file()
        entry = f['entry']
        from mcvine.instruments.HYSPEC.nxs.raw import populateMetadata
        populateMetadata(entry, sim_out, sample, detector)
        return
    
    
    def _nxs_file(self):
        import h5py
        return h5py.File(self.inventory.nxs, 'a')


    def help(self):
        print cmd_help
    

def main():
    app = App(appname)
    app.run()
    return


if __name__ == '__main__': main()
