#!/usr/bin/env python
import warnings
warnings.simplefilter('ignore')
import mcvine
warnings.simplefilter('default')

def main():
    from mcvine.instruments.HYSPEC.Instrument import Instrument
    app = Instrument('hyspec_moderator2sample')
    app.run()
    return

if __name__ == '__main__': main()
