#!/usr/bin/env python


from mcvine.instruments.SNS.applications.Neutrons2Events import App as base
appname = 'hyspec-neutrons2events'


# application 
class App(base):

    def _defaults(self):
        super(App, self)._defaults()
        import os    
        xml = os.path.join(mcvinedir, 'share', 'mcvine', 'instruments', 'hyspec', 'hyspec.xml.fornxs')
        self.inventory.detsys = xml
        return


def main():
    app = App(appname)
    app.run()
    return

if __name__ == '__main__': main()
