FROM phusion/baseimage

MAINTAINER "Jiao Lin <jiao.lin@gmail.com>"

LABEL Description="image to install MCViNE"

RUN curl -s https://packagecloud.io/install/repositories/danse/ins/script.deb.sh | bash
RUN apt-get install -qy mcvine
