#!/usr/bin/env python
import warnings
warnings.simplefilter('ignore')
import mcvine
warnings.simplefilter('default')

def main():
    from mcvine.applications.InstrumentBuilder import build
    components = ['moderator', 'core_vessel_insert', 'shutter_guide', 'guide111', 'guide112', 'guide113', 'guide121', 'guide122', 'guide123', 'guide131', 'guide132', 'guide133', 't0chopper', 'guide211', 'guide212', 'guide213', 'guide214', 'guide215', 'fermichopper', 'monitor1', 'guide311', 'guide411', 'guide412', 'guide511', 'monitor']
    App = build(components)
    app = App('arcs_moderator2sample')
    app.run()
    return

if __name__ == '__main__': main()

# This application was created by the following command:
# $ mcvine-create-instrument-simulation-application -name=arcs_moderator2sample --components=moderator,core_vessel_insert,shutter_guide,guide111,guide112,guide113,guide121,guide122,guide123,guide131,guide132,guide133,t0chopper,guide211,guide212,guide213,guide214,guide215,fermichopper,monitor1,guide311,guide411,guide412,guide511,monitor

