#!/usr/bin/env python

appname = 'arcs-compute-IQE-resolution'

def execute(cmd):
    import os
    print '* executing %s... ' % cmd
    if os.system(cmd):
        raise RuntimeError, "%r failed" % cmd


def run(
    workdir = 'work',
    ncount=1e7, nodes=5, 
    Ei=None,
    Q=10, E=100, dQ=1, dE=10, 
    incident_neutrons = None,
    mod2sample='../mod2sample',
    ):
    
    import os
    #
    _init(workdir)
    #
    os.chdir(workdir)

    # Ei
    Ei_user = Ei
    Ei = _computeAverageEnergy(mod2sample_outdir=mod2sample)
    if Ei_user is not None and abs(Ei-Ei_user)/Ei > 0.1:
        raise ValueError, "nominal energy %s is too different from average energy at sample position %s" % (Ei_user, Ei)

    # make sure E and Q are in the correct ranges
    if E <= 0 or E >= Ei:
        raise ValueError, "E should be in the range of (0, Ei=%s)" % (
            Ei,)
    from mcni.utils import conversion
    Qi = conversion.e2k(Ei)
    if Q <= 0 or Q >= 2*Qi:
        raise ValueError, "Q should be in the range of (0, 2*Qi=%s)" % (
            2*Qi,)

    # make sure we have sound resolution
    if dQ == 0:
        dQ = Q/10.
    if dE == 0:
        dE = E/10.
        
    #
    if incident_neutrons is None:
        incident_neutrons = os.path.join(mod2sample, 'neutrons')
    if not os.path.exists(incident_neutrons):
        raise IOError, "incident neutrons file %r does not exist" % (
            incident_neutrons, )
    
    # create scattering kernel file
    createScatteringKernel(Q,E)
    
    # run main sim
    cmd = './sssd --source.path="%s" --ncount=%s --mpirun.nodes=%s' % (
        incident_neutrons, ncount, nodes)
    execute(cmd)

    # reduce events to S(Q,E)
    eventsdat = 'out/events.dat'
    dQ/=2.; dE/=2.
    Qaxis = Q-dQ, Q+dQ, dQ/50.
    Eaxis = E-dE, E+dE, dE/50.
    Ei, toffset = getEiToffset(mod2sample)
    iqe = reduceToIQE(eventsdat, Ei, toffset, Qaxis, Eaxis)
    from histogram.hdf import dump
    dump(iqe, 'iqe.h5', '/', 'c')
    global interactive
    if interactive:
        from histogram.plotter import defaultPlotter
        defaultPlotter.plot(iqe)
    return


mod2sample_distance = 13.6
def getEiToffset(mod2sample):
    from histogram.hdf import load
    import os

    # I(energy)
    ie = load(os.path.join(mod2sample, 'ienergy.h5'),
              'ienergy')
    # average energy
    e = (ie.I * ie.energy).sum()/ie.I.sum()
    
    # I(tof)
    itof = load(os.path.join(mod2sample, 'itof.h5'),
                'itof')
    # average tof
    tof = (itof.I*itof.tof).sum()/itof.I.sum()
    
    from mcni.utils.conversion import e2v
    v = e2v(e)
    
    L = mod2sample_distance
    toffset = tof - (L/v)
    # energy: meV, toffset: microsecond
    return e, toffset * 1e6


def createScatteringKernel(Q,E):
    import os
    tf = os.path.join('sampleassembly', 'Al-scatterer.xml.template')
    t = open(tf).read()
    t = t.replace('$Q$', '%s/angstrom' % Q)
    t = t.replace('$E$', '%s*meV' % E)
    
    f = os.path.join('sampleassembly', 'Al-scatterer.xml')
    open(f, 'w').write(t)
    return 


# constants
import pyre.units.length
import pyre.units.energy
import pyre.units.time
npixels = 117760 # number of pixels for ARCS
mod2sample=13.6*pyre.units.length.meter
mod_period=0.015*pyre.units.time.s # moderator period
def reduceToIQE(eventsfile, Ei, toffset, Qaxis, Eaxis):
    from mccomponents.detector.reduction_utils import events2IQE
    from mccomponents.detector.event_utils import datatype
    import os
    nevents = os.path.getsize(eventsfile)*1. / datatype.itemsize
    assert int(nevents) - nevents == 0
    
    outfile = 'intensities.dat'
    pixelpositionsfile = 'pixelID2position.bin'
    solidanglesfile = 'solidangles.bin'
    iqe = events2IQE(
        eventsfile, nevents, 
        outfile,
        pixelpositionsfile, solidanglesfile, npixels,
        mod2sample=mod2sample,
        Ei=Ei*pyre.units.energy.meV,
        Qaxis=Qaxis, Eaxis=Eaxis,
        tofUnit=1*pyre.units.time.microsecond,
        toffset=toffset*pyre.units.time.microsecond,
        tofmax=mod_period,
        )
    return iqe


def _init(dir):
    """initialized the directory to contain necessary files 
    for this simulation

    * ARCS.xml
    * pixelID2position.bin
    * solidangles.bin
    * sampleassembly
    * sssd, sssd.pml
    """
    import shutil, os
    # mcvine export root
    export_root = os.environ['MCVINE_DIR']
    # arcs resource directory
    from mcvine import resources
    res_dir = os.path.join(resources.instrument('ARCS'), resources)
    # src
    src = os.path.join(res_dir, appname)
    # 
    shutil.copytree(src, dir)
    return

    
def _computeAverageEnergy(ienergyh5=None, mod2sample_outdir=None):

    from histogram.hdf import load
    import os
    
    if ienergyh5 is None:
        ienergyh5 = os.path.join(mod2sample_outdir, 'ienergy.h5')

    h = load(ienergyh5, 'ienergy')
    e = (h.energy * h.I).sum()/h.I.sum()
    
    return e


app_help = """
%s --ncount=1e7 --nodes=10 --Ei=100 --Q=6  --E=20 --dQ=1 --dE=10 --mod2sample=/path/to/mod2sample
""" % appname
from pyre.applications.Script import Script as AppBase
class App(AppBase):

    class Inventory(AppBase.Inventory):

        import pyre.inventory
        workdir = pyre.inventory.str('workdir', default='work')
        ncount = pyre.inventory.float('ncount', default=1e7)
        nodes = pyre.inventory.int('nodes', default=1)
        Ei = pyre.inventory.float('Ei', default=0)
        Q = pyre.inventory.float('Q', default=10)
        E = pyre.inventory.float('E', default=100)
        dQ = pyre.inventory.float('dQ', default=0)
        dE = pyre.inventory.float('dE', default=0)
        mod2sample = pyre.inventory.str('mod2sample', default='../mod2sample')


    def help(self):
        print app_help

        
    def main(self):
        ncount = self.inventory.ncount
        nodes = self.inventory.nodes
        Ei = self.inventory.Ei
        Q = self.inventory.Q
        E = self.inventory.E
        dQ = self.inventory.dQ
        dE = self.inventory.dE
        mod2sample = self.inventory.mod2sample
        import os
        mod2sample = os.path.expanduser(mod2sample)
        
        if Ei == 0:
            Ei = None
        
        # run
        run(
            ncount=ncount, nodes=nodes, 
            Ei=Ei, Q=Q, E=E, dQ=dQ, dE=dE,
            mod2sample = mod2sample,
            )
        return
    

def main():
    app = App(appname)
    app.run()
    return


interactive = False

if __name__ == '__main__': 
    interactive = True
    main()
