name: CI

env: {"CI_NAME": "github-actions"}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  #schedule:
  #  - cron: "50 14 * * *"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        #python-version: ["3.10"]
    steps:
      #- name: install glut
      #  run: sudo apt-get update && sudo apt-get install -y procps freeglut3-dev libglu1-mesa unzip
      # setup conda
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          auto-update-conda: true
          environment-file: mcvine-dev.yml
          condarc: |
            channels:
                - neutrons/label/rc
                - neutrons
                - mantid
                - mcvine
                - conda-forge
                - diffpy
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}        
      # build and test (have to use pwsh!)
      - name: build / test / upload
        shell: pwsh
        run: |
          echo $PYTHON_VERSION
          ./builders/CI/build_and_test.sh
        env:
          ANACONDA_UPLOAD_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          #PYTHON_VERSION: ${{ matrix.python-version }}
