name: CI

env: {"CI_NAME": "github-actions"}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  #schedule:
  #  - cron: "50 14 * * *"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: system update
        run:
          sudo apt-get update && sudo apt-get upgrade -y
      - name: install glut
        run: sudo apt-get install -y procps freeglut3-dev libglu1-mesa unzip

      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      # setup conda
      - uses: conda-incubator/setup-miniconda@v3
        with:
          #auto-update-conda: true
          environment-file: mcvine-dev.yml
          condarc: |
            channels:
                - neutrons/label/rc
                - neutrons
                - mantid
                - mcvine
                - conda-forge
                - diffpy
          fetch-depth: 0        
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      #- name: Check out source code
        #uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}        
      # build and test (have to use pwsh!)
      - name: build / test / upload
        #shell: pwsh
        run: |
          echo $CONDA_PREFIX
          ./builders/CI/build_and_test.sh
      - name: Deploy to Anaconda
        shell: bash -l {0}
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is dev or rc depending on the tag-name
          CONDA_LABEL="dev"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          CONDA_ROOT_PREFIX=$(realpath $(dirname `which conda`)/..)
          echo $CONDA_ROOT_PREFIX
          anaconda upload --label $CONDA_LABEL --user mcvine $CONDA_ROOT_PREFIX/conda-bld/linux-64/mcvine-core-$MCVINE_CONDA_PKG_VER-*.conda
