name: CI

env: {"CI_NAME": "github-actions"}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "50 14 * * *"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: system update
        run:
          sudo apt-get update && sudo apt-get upgrade -y
      - name: install glut
        run: sudo apt-get install -y procps freeglut3-dev libglu1-mesa unzip

      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      # setup miniconda
      - name: Miniconda    
        uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-update-conda: true
          environment-file: environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Miniconda info
        shell: bash -l {0}
        run: conda info
      # build and test (have to use pwsh!)
      - name: build / test
        shell: bash -l {0}
        run: |
          echo $PYTHON_VERSION
          ./builders/CI/build_and_test.sh
