name: CI

env: {"CI_NAME": "github-actions"}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "50 14 * * *"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: system update
        run:
          sudo apt-get update && sudo apt-get upgrade -y
      - name: install glut
        run: sudo apt-get install -y procps freeglut3-dev libglu1-mesa unzip

      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Branch-Commit Information
        id: get_commit
        run: |
          echo running on branch ${GITHUB_HEAD_REF##*/}
          echo "latest_commit_id=$(git log -1 --format=%H)" >> "$GITHUB_OUTPUT"

      # setup micromamba
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      # build and test (have to use pwsh!)
      - name: build / test
        shell: bash -l {0}
        run: |
          echo $PYTHON_VERSION
          export GIT_FULL_HASH=${{ steps.get_commit.outputs.latest_commit_id }}"
          ./builders/CI/build_and_test.sh
